---
- hosts: "{{ server | default('production') }}"
  tasks:
    - name: start_confluent-kafka-connect
      service:
        name: confluent-kafka-connect
        state: started

# vim: et sw=2 ts=2:
