---
- hosts: "{{ server | default('production') }}"
  tasks:
    - name: start_confluent-control-center
      service:
        name: confluent-control-center
        state: started

# vim: et sw=2 ts=2:
