---
- hosts: "{{ server | default('production') }}"
  tasks:
    - name: stop_confluent-kafka-connect
      service:
        name: confluent-kafka-connect
        state: stopped

# vim: et sw=2 ts=2:
