---
- hosts: "{{ server | default('production') }}"
  tasks:
    - name: stop_confluent-control-center
      service:
        name: confluent-control-center
        state: stopped

# vim: et sw=2 ts=2:
