---
# tasks file for confluent_standalone
- block:

  - name: import_key
    rpm_key:
      state: present
      key: https://packages.confluent.io/rpm/5.5/archive.key

  - name: copy_repo
    template:
      src: cp.repo.j2
      dest: /etc/yum.repos.d/cp.repo

  - name: install_confluent-platform-2.12
    yum:
      name: confluent-platform-2.12
      state: installed
      update_cache: yes

  - name: install cli
    shell:
      cmd: curl -L https://cnfl.io/cli | sh -s -- -b /usr/local/bin
      creates: "/usr/local/bin/confluent"

  tags:
    - confluent_standalone

# vim: et ts=2 sw=2:
