---
# tasks file for confluent_standalone
- block:

  - name: import_key
    rpm_key:
      state: present
      key: https://packages.confluent.io/rpm/5.5/archive.key

  - name: copy_repo
    template:
      src: cp.repo.j2
      dest: /etc/yum.repos.d/cp.repo

  - name: install_confluent-platform-2.12
    yum:
      name: confluent-platform-2.12
      state: installed
      update_cache: yes

  - name: template_server.properties
    template:
      src: server.properties.j2
      dest: /etc/kafka/server.properties

  - name: template_ksql-server.properties
    template:
      src: ksql-server.properties.j2
      dest: /etc/ksqldb/ksql-server.properties

  - name: template_schema-registory.properties
    template:
      src: schema-registry.properties.j2
      dest: /etc/schema-registry/schema-registry.properties

  - name: template_control-center.properties.j2
    template:
      src: control-center.properties.j2
      dest: /etc/confluent-control-center/control-center-production.properties

  - name: mkdir_/var/lib/kafka-streams
    file:
      path: /var/lib/kafka-streams
      state: directory
      owner: cp-kafka
      group: confluent
      mode: 0775

  - name: install cli
    shell:
      cmd: curl -L https://cnfl.io/cli | sh -s -- -b /usr/local/bin
      creates: "/usr/local/bin/confluent"

  tags:
    - confluent_standalone

# vim: et ts=2 sw=2:
